// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3932.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.CommandGroup;

import org.usfirst.frc3932.Robot;
import org.usfirst.frc3932.subsystems.*;

/**
 *
 */
public class TurnTo30Degrees extends Command {
	TurnTo t;
	
	public TurnTo30Degrees() {
		requires(Robot.driveSystem);
	}
	
	public void initialize(){
		t = new TurnTo(30);
		t.initialize();
	}
	
	public void execute() {
		
	}
	
	public boolean isFinished() {
		return t.isFinished();
	}
	
	public void end() {
		t.end();
	}
	
	public void interrupted() {
		t.interrupted();
	}
}
